---
title: "D1 Power Rankings"
author: "Samuel Ivanecky"
date: "1/11/2020"
output: html_document
---

```{r setup, include=FALSE}
# Libraries
library(ggplot2)
library(tidyverse)
library(data.table)
library(rvest)
library(forecast)

# Set WD
setwd("~/Desktop/XC/Running/")
```

# readPerfList
```{r}
# Function to read in webpage and produce a dataframe of scored athletes
readPerfList = function(url){
  # Read in webpage HTML
  # Get HTML
  webpage = read_html(url)

  # Read in tables
  tables = html_table(webpage)
  
  # Extract first df
  results = as.data.frame(tables[1])
  names(results) = c("PLACE", "ATHLETE", "YEAR", "TEAM", "TIME", "MEET", "MEET.DATE")
  
  # Create gender column
  results$Gender = "M"
  
  # Table for relays data
  relays = data.frame()
  
  # Extract all the tables into dataframes
  for( i in 2:length(tables) )
  {
    # Temporary df
    temp = as.data.frame(tables[i])
    # Make sure table has 7 columns for binding - some tables using conversions for field events have 8 columns
    if ( ncol(temp) == 7 )
    { 
      # Rename and bind
      names(temp) = c("PLACE", "ATHLETE", "YEAR", "TEAM", "TIME", "MEET", "MEET.DATE")
      
      # Check to assign gender - womens tables should be "even" numbers
      if ( i%%2 == 0 ) 
      { 
        temp$Gender = "F" 
      }
      else { temp$Gender = "M" }
      
      results = rbind(results, temp) 
    }
    else if( ncol(temp) == 6)
    {
      relays = rbind(relays, temp)
    }
  }
  
  # Events are not tied in to data - need to add them based on times
  results = results %>%
    mutate(EVENT = case_when(
      grepl('6\\.|7\\.', TIME) & (substr(TIME,1,1) %in% c('6','7')) ~ '60m', # Have to add the substr clause to get only those that start with a 6
      grepl('21\\.|22\\.|23\\.|24\\.|25\\.|26\\.', TIME) & (substr(TIME,1,2) %in% c('21','22','23','24','25','26')) ~ '200m',
      grepl('44\\.|45\\.|46\\.|47\\.|48\\.|49\\.|50\\.|51\\.|52\\.|53\\.|54\\.|55\\.|56\\.|57\\.|58\\.|59\\.', TIME) & 
        (substr(TIME,1,2) %in% c('44','45','46','47','48','49','50','51','52','53','54','55','56','57','58','59')) ~ '400m',
      grepl('1:|2:', TIME) & (substr(TIME,1,2) %in% c('1:','2:')) ~ '800m',
      grepl('3:|4:|5:', TIME) & (substr(TIME,1,2) %in% c('3:','4:','5:')) ~ 'Mile',
      grepl('7:|8:|9:|10:|11:', TIME) & (substr(TIME,1,2) %in% c('7:', '8:', '9:', '10', '11')) ~ '3000m',
      grepl('13:|14:|15:|16:|17:|18:', TIME) & (substr(TIME,1,3) %in% c('13:','14:','15:','16:','17:','18:')) ~ '5000m',
      T ~ 'OTHER'
    ))
  
  # Subset to Top 40 per event
  results = results %>%
  filter(EVENT %in% c('800m', 'Mile', '3000m', '5000m')) %>%
  mutate(
    PTS = 101 - PLACE
  )
  
  # Group to one line per runner
  pts_grp = results %>%
  group_by(ATHLETE) %>%
  summarise(TEAM = max(TEAM), YEAR = max(YEAR), GENDER = max(Gender), POINTS = sum(PTS, na.rm = T), EVENTS = n_distinct(EVENT)) %>%
  mutate(PTS_PER_EVENT = POINTS / EVENTS) %>%
  arrange(-POINTS)
  
  # Return dataframe
  return(pts_grp)
}
```

# Get 2019 & 2020 perf lists
```{r}
# Current performance lists
rank2020 = readPerfList('https://www.tfrrs.org/lists/2770/2019_2020_NCAA_Div._I_Indoor_Qualifying/2020/i')
rank2019 = readPerfList('https://www.tfrrs.org/lists/2324/2018_2019_NCAA_Div._I_Indoor_Qualifying_(FINAL)/2019/i')
```

# Join 2019 to 2020
```{r}
# Rename columns in 2019
names(rank2019) = c("ATHLETE", "TEAM", "YEAR", "GENDER", "POINTS_19", "EVENTS_19", "PTS_PER_EVENT_19")

# Select only required columns
rank2019 = rank2019 %>%
  select(ATHLETE, POINTS_19, EVENTS_19, PTS_PER_EVENT_19)

# Join tables
rank2020 = rank2020 %>%
  left_join(rank2019, by = c("ATHLETE"))
```

# Clean 2020 data
```{r}
# Change NAs produced by join to 0
rank2020 = rank2020 %>%
  mutate(
    POINTS_19 = ifelse(is.na(POINTS_19), 0, POINTS_19),
    EVENTS_19 = ifelse(is.na(EVENTS_19), 0, EVENTS_19),
    PTS_PER_EVENT_19 = ifelse(is.na(PTS_PER_EVENT_19), 0, PTS_PER_EVENT_19)
  ) %>%
  mutate(
    PTS_PER_EVENT = round(PTS_PER_EVENT, 2),
    PTS_PER_EVENT_19 = round(PTS_PER_EVENT_19, 2)
  )
```

# Split by Gender
```{r}
men2020 = rank2020 %>% filter(GENDER == 'M')
women2020 = rank2020 %>% filter(GENDER == 'F')
```

# Algorithm to assign points
```{r}
getRank = function(df){
  # Extract maximum total of any runner in each year
  maxPts20 = max(df$POINTS)
  maxPts19 = max(df$POINTS_19)
  # Extract maximum points per event for each year
  maxPtsPerEvent20 = max(df$PTS_PER_EVENT)
  maxPtsPerEvent19 = max(df$PTS_PER_EVENT_19)
  
  # Create RANK value
  df = df %>%
    mutate(
      RANK = ((POINTS / maxPts20) * 50) +
        ((POINTS_19 / maxPts19) * 30) + 
        ((PTS_PER_EVENT / maxPtsPerEvent20) * 10) + 
        ((PTS_PER_EVENT_19 / maxPtsPerEvent19) * 10)
    ) %>%
    arrange(-RANK) %>%
    mutate(
      RANK = round(RANK, 2)
    ) %>%
    select(ATHLETE, TEAM, YEAR, GENDER, RANK)
  
  # Subset to top 100
  df = df[1:100, ]
  
  # Return df
  return(df)
}
```

# Rank 2020 runners
```{r}
men2020 = getRank(men2020)
women2020 = getRank(women2020)
```
