---
title: "D2 Power Rankings"
author: "Samuel Ivanecky"
date: "1/9/2020"
output: html_document
---

```{r setup, include=FALSE}
# Libraries
library(ggplot2)
library(tidyverse)
library(data.table)
library(rvest)
library(forecast)

# Set WD
setwd("~/Desktop/XC/Running/")
```

# READ IN WEBPAGE FROM TFRRS
```{r}
# Read in TFRRS page
url = 'https://www.tfrrs.org/lists/2771/2019_2020_NCAA_Div._II_Indoor_Qualifying/2020/i?gender=f'

# Get HTML
webpage = read_html(url)

# Read in tables
tables = html_table(webpage)
```

# EXTRACT TABLES FROM HTML
```{r}
# Extract first df
results = as.data.frame(tables[1])
names(results) = c("PLACE", "ATHLETE", "YEAR", "TEAM", "TIME", "MEET", "MEET.DATE")

# Create gender column
results$Gender = "M"

# Table for relays data
relays = data.frame()

# Extract all the tables into dataframes
for( i in 2:length(tables) )
{
  # Temporary df
  temp = as.data.frame(tables[i])
  # Make sure table has 7 columns for binding - some tables using conversions for field events have 8 columns
  if ( ncol(temp) == 7 )
  { 
    # Rename and bind
    names(temp) = c("PLACE", "ATHLETE", "YEAR", "TEAM", "TIME", "MEET", "MEET.DATE")
    
    # Check to assign gender - womens tables should be "even" numbers
    if ( i%%2 == 0 ) 
    { 
      temp$Gender = "F" 
    }
    else { temp$Gender = "M" }
    
    results = rbind(results, temp) 
  }
  else if( ncol(temp) == 6)
  {
    relays = rbind(relays, temp)
  }
}
```

# ASSIGN EVENTS TO EACH RESULT
```{r}
# Events are not tied in to data - need to add them based on times
results = results %>%
  mutate(EVENT = case_when(
    grepl('6\\.|7\\.', TIME) & (substr(TIME,1,1) %in% c('6','7')) ~ '60m', # Have to add the substr clause to get only those that start with a 6
    grepl('21\\.|22\\.|23\\.|24\\.|25\\.|26\\.', TIME) & (substr(TIME,1,2) %in% c('21','22','23','24','25','26')) ~ '200m',
    grepl('44\\.|45\\.|46\\.|47\\.|48\\.|49\\.|50\\.|51\\.|52\\.|53\\.|54\\.|55\\.|56\\.|57\\.|58\\.|59\\.', TIME) & 
      (substr(TIME,1,2) %in% c('44','45','46','47','48','49','50','51','52','53','54','55','56','57','58','59')) ~ '400m',
    grepl('1:|2:', TIME) & (substr(TIME,1,2) %in% c('1:','2:')) ~ '800m',
    grepl('3:|4:|5:', TIME) & (substr(TIME,1,2) %in% c('3:','4:','5:')) ~ 'Mile',
    grepl('7:|8:|9:|10:|11:', TIME) & (substr(TIME,1,2) %in% c('7:', '8:', '9:', '10', '11')) ~ '3000m',
    grepl('13:|14:|15:|16:|17:|18:', TIME) & (substr(TIME,1,3) %in% c('13:','14:','15:','16:','17:','18:')) ~ '5000m',
    T ~ 'OTHER'
  ))
```

# HANDLE RELAYS TABLE
```{r}
relays = relays %>%
  mutate(EVENT = case_when(
    grepl('3:|4:', TIME) & (substr(TIME,1,2) %in% c('3:','4:')) ~ '4x400m',
    grepl('9:|10:|11:|12:|13:|14:|15:|16:', TIME) & (substr(TIME,1,2) %in% c('9:','10','11','12','13','14','15','16')) ~ 'DMR',
    T ~ 'OTHER'
  ))
```

# ASSIGN POINTS TO EACH ATHLETE
## FILTER OUT ATHLETES OUTSIDE THE TOP 40 & ONLY DISTANCE
```{r}
top40 = results %>%
  filter(PLACE <= 40) %>%
  filter(EVENT %in% c('800m', 'Mile', '3000m', '5000m'))
  
```

## GIVE PTS TO RUNNERS
```{r}
top40 = top40 %>%
  mutate(
    PTS = 41 - PLACE
  )
```

# GROUP TO ATHLETE LEVEL
```{r}
pts_grp = top40 %>%
  group_by(ATHLETE) %>%
  summarise(TEAM = max(TEAM), YEAR = max(YEAR), GENDER = max(Gender), POINTS = sum(PTS, na.rm = T), EVENTS = n_distinct(EVENT)) %>%
  mutate(PTS_PER_EVENT = POINTS / EVENTS) %>%
  arrange(-PTS_PER_EVENT)
```

## SPLIT BY GENDER
```{r}
top_men = pts_grp %>%
  filter(GENDER == 'M')

top_women = pts_grp %>%
  filter(GENDER == 'F')
```




