---
title: "Waiver Wire"
author: "Samuel Ivanecky"
date: "1/19/2020"
output: html_document
---
```{r setup, include=FALSE}
# Libraries
library(ggplot2)
library(tidyverse)
library(data.table)
library(rvest)
library(forecast)

# Set WD
setwd("~/Desktop/XC/Running/")
```

# readPerfList
```{r}
# Function to read in webpage and produce a dataframe of scored athletes
readPerfList = function(url){
  # Read in webpage HTML
  # Get HTML
  webpage = read_html(url)

  # Read in tables
  tables = html_table(webpage)
  
  # Extract first df
  results = as.data.frame(tables[1])
  names(results) = c("PLACE", "ATHLETE", "YEAR", "TEAM", "TIME", "MEET", "MEET.DATE")
  
  # Create gender column
  results$Gender = "M"
  
  # Table for relays data
  relays = data.frame()
  
  # Extract all the tables into dataframes
  for( i in 2:length(tables) )
  {
    # Temporary df
    temp = as.data.frame(tables[i])
    # Make sure table has 7 columns for binding - some tables using conversions for field events have 8 columns
    if ( ncol(temp) == 7 )
    { 
      # Rename and bind
      names(temp) = c("PLACE", "ATHLETE", "YEAR", "TEAM", "TIME", "MEET", "MEET.DATE")
      
      # Check to assign gender - womens tables should be "even" numbers
      if ( i%%2 == 0 ) 
      { 
        temp$Gender = "F" 
      }
      else { temp$Gender = "M" }
      
      results = rbind(results, temp) 
    }
    else if( ncol(temp) == 6)
    {
      relays = rbind(relays, temp)
    }
  }
  
  # Events are not tied in to data - need to add them based on times
  results = results %>%
    mutate(EVENT = case_when(
      grepl('6\\.|7\\.', TIME) & (substr(TIME,1,1) %in% c('6','7')) ~ '60m', # Have to add the substr clause to get only those that start with a 6
      grepl('21\\.|22\\.|23\\.|24\\.|25\\.|26\\.', TIME) & (substr(TIME,1,2) %in% c('21','22','23','24','25','26')) ~ '200m',
      grepl('44\\.|45\\.|46\\.|47\\.|48\\.|49\\.|50\\.|51\\.|52\\.|53\\.|54\\.|55\\.|56\\.|57\\.|58\\.|59\\.', TIME) & 
        (substr(TIME,1,2) %in% c('44','45','46','47','48','49','50','51','52','53','54','55','56','57','58','59')) ~ '400m',
      grepl('1:|2:', TIME) & (substr(TIME,1,2) %in% c('1:','2:')) ~ '800m',
      grepl('3:|4:|5:', TIME) & (substr(TIME,1,2) %in% c('3:','4:','5:')) ~ 'Mile',
      grepl('7:|8:|9:|10:|11:', TIME) & (substr(TIME,1,2) %in% c('7:', '8:', '9:', '10', '11')) ~ '3000m',
      grepl('13:|14:|15:|16:|17:|18:', TIME) & (substr(TIME,1,3) %in% c('13:','14:','15:','16:','17:','18:')) ~ '5000m',
      T ~ 'OTHER'
    ))
  
  # Subset to Top 40 per event
  results = results %>%
  filter(EVENT %in% c('800m', 'Mile', '3000m', '5000m')) %>%
  mutate(
    PTS = 101 - PLACE
  )
  
  # Return dataframe
  return(results)
}
```

# Get 2020 Performance List
```{r}
rank2020 = readPerfList('https://www.tfrrs.org/lists/2770/2019_2020_NCAA_Div._I_Indoor_Qualifying/2020/i') %>%
  select(ATHLETE, PLACE)
```

# Fix name
```{r}
rank2020 = separate(rank2020, ATHLETE, c("LAST", "FIRST"), sep = ", ")
rank2020 = rank2020 %>%
  mutate(
    NAME = paste0(FIRST, " ", LAST)
  ) %>%
  select(NAME, PLACE)
```

# Read in current teams
```{r}
mens_draft = read.csv("Mens_Draft.csv")
womens_draft = read.csv("Womens_Draft.csv")
```

# Join results
```{r}
# Group to one row per runner
ranked_runners = rank2020 %>% 
  group_by(NAME) %>%
  summarise(PLACE = min(PLACE))
```

```{r}
# Convert names to lower
ranked_runners$NAME = tolower(ranked_runners$NAME)
mens_draft$Runner = tolower(mens_draft$Runner)
womens_draft$Runner = tolower(womens_draft$Runner)
# Join runners to teams
mens_teams = mens_draft %>%
  left_join(ranked_runners, by = c("Runner" = "NAME"))
womens_teams = womens_draft %>%
  left_join(ranked_runners, by = c("Runner" = "NAME"))
```

```{r}
# Fix NA points
mens_teams$PLACE = ifelse(is.na(mens_teams$PLACE), 101, mens_teams$PLACE)
womens_teams$PLACE = ifelse(is.na(womens_teams$PLACE), 101, womens_teams$PLACE)
```

# Get waiver wire
```{r}
mens_wire = mens_teams %>%
  group_by(Team) %>%
  summarise(Points = sum(PLACE)) %>%
  arrange(-Points)

womens_wire = womens_teams %>%
  group_by(Team) %>%
  summarise(Points = sum(PLACE)) %>%
  arrange(-Points)
```






